# Zero reais de Funções reais

In [13]:
import math
from tabulate import tabulate
import time
import pandas as pd

## A $)$

### Método da Bissecção

#### Explicação do Método da Bissecção:

Dada uma função $f(x)$ ela tem de ser contínua num intervalo $[a,b]$, de forma que $f(a)\cdot f(b) < 0$.

O objetivo do método da Bissecção é diminuir a abrangência do dado intervalo que contém uma raíz até alcançar uma precisão determinada.   
Se assume que o intervalo dado tenha apenas uma raíz para a dada função $f(x) = 0$.  

Adiante, isso ocorre da seguinte forma: $ (b-a) < \epsilon$, essa condição é testada múltiplas vezes por meio da divisão iterativa do intervalo ao meio. 

O valor de a pode aumentar e o de b pode diminuir, a fim de diminuir o intervalo, logicamente restringindo o intervalo de valores onde a raíz pode estar. O método não é exato, em razão disso existe o $\epsilon$ que determina uma precisão, que seria um valor de intervalo aceitável onde a raíz pode estar situada.  
Esse método tem a desvantagem de ter uma convergência lenta para problemas mais complexos, que exigem um alto número de iterações para chegar em um resultado aceitável.

<div style="display: flex; justify-content: center; gap: 20px;">
  <img src="assets/atv_3/BSC_a.png" width="400">
</div>

Complexidade do Método da Bissecção:  
A estimativa do número de iterações, partindo do presuposto que $k$ satisfaz a seguinte relação:

$$ k > \frac{log(b_0 - a_0) - log(\epsilon)}{log(2)} $$

Os logaritmos usam base 10, então $log(2) = 0.3010$.  
Essa estimativa serve para calcular o mínimo de iterações necessárias para encontrar a raíz da função, antes mesmo de efetuar o cálculo do problema.

In [449]:
# Dado um intervalo inicial [1,2] 
def Estimativa_Bisseccao(intervalo, precisao):
    a = intervalo[0]
    b = intervalo[1]

    estimativa = (math.log10(b-a) - math.log10(precisao)/ math.log10(2))
    print(f"O número provável de iterações é: ({round(estimativa)})") 

Estimativa_Bisseccao([1,2], 10**(-6))

O número provável de iterações é: (20)

Código para o Método da Bissecção

In [450]:
# Algoritmo 1
# Código do Método da Bisseção

# função para teste
def funcao(x):
    return x**3 - x - 1                                               
                                               # Linha 1: Os dados iniciais                                              
interval = [1.0, 2.0]                          # O intervalo Inicial [a,b]
e = 10**(-6)                                   # precisão ε

# função propriamente

def bisseccao(func, interv, e, p):
    k = 0
    a = interv[0]
    b = interv[1]
    total_i = []
    tempo_t = []

    if abs(b-a) < e:                           # Linha 2: Condição para parada antes de iniciar a função, optei por usar o valor central entre o intervalo
        xi = (a+b)/2
        return {"Método": "Bissecção", "Raíz x̅": f"{xi:.8f}", "F(x̅)": f"{func(xi):.13f}", "Erro em X": 0, "N° de Iterações": 0, "Operações/Iteração": 0, "Total de Operações": 0, "Tempo Total": 0, "Tempo/Iteração": 0}
        # return xi

    k = 1                                      # Linha 3: Introdução de um iterador na função

    while abs(b-a) > e:
        time_inicial = time.perf_counter()
        i = 0

        M = func(a)                            # Linha 4: variável para armazenar o valor de f(a)                                  
        x = (a + b)/2                          # Linha 5: Média da distância entre os intervalos
        i += 8

        if (func(x)*M) > 0:                    # Linha 6: Condição para que a = x
            a = x  
            i += 4
            if (b - a) < e:                    # Linha 8: Condição de parada
                xi = (a+b)/2
                i += 5
                total_i.append(i)              # Adiciona todos as operações a uma lista e tira a média do total de operações por iteração
                media_i = round((sum(total_i))/k)    
                time_final = time.perf_counter()
                tempo_t.append(time_final - time_inicial)    
                error = abs(b-a)                         
                if p == 1:                     # Print com Tabulate
                    resultados = [ ["Método", "Bissecção"], ["Dados Iniciais", f"[{interv[0]}, {interv[1]}]"], ["x̅ (raiz aproximada)", f"{xi:.8f}"], ["f(x̅)", f"{func(x):.13f}"], ["Erro x̅", f"{error:.13f}"], ["Iterações", k], ["Operações Média", media_i], ["Operação Total", sum(total_i)], ["Tempo Total", f"{sum(tempo_t):.12f}s"], ["Tempo por Iteração", f"{(sum(tempo_t) / k):.12f}s"]]
                    print("\n" + "="*42+"\n            MÉTODO DA BISSECÇÃO\n"+"="*42)
                    print(tabulate(resultados, tablefmt="fancy_grid")) 
                    print("="*42 + "\n")       # O retorno é o x̅, o número de iterações, o valor da função em x e o erro em x(b-a)   
                    break
                    
                else:
                    return {"Método": "Bissecção", "Dados Iniciais": f"[{interv[0]},{interv[1]}]","Raíz x̅": f"{x:.8f}", "F(x̅)": f"{func(x):.13f}", "Erro em X": f"{error:.13f}", "N° de Iterações": k, "Operações/Iteração": media_i, "Total de Operações": sum(total_i), "Tempo Total": f"{sum(tempo_t):.12f}s", "Tempo/Iteração": f"{(sum(tempo_t)/k):.12f}s"}
                    # return x, k, func(x), (b-a)
            else:
                k += 1                         # Linha 9: Aumento da contagem do Iterador
                total_i.append(i)
                time_final = time.perf_counter()
                tempo_t.append(time_final - time_inicial) 
        else: 
            k += 1                             # Linha 9: Aumento da contagem do Iterador
            b = x                              # Linha 7: b = x
            i += 1
            total_i.append(i)
            time_final = time.perf_counter()
            tempo_t.append(time_final - time_inicial) 
                                               # Adição de contadores para o número de 
    return {"Método": "Bissecção", "Dados Iniciais": f"[{interv[0]},{interv[1]}]","Raíz x̅": f"{x:.8f}", "F(x̅)": f"{func(x):.13f}", "Erro em X": f"{(b-a):.13f}", "N° de Iterações": k, "Operações/Iteração": round((sum(total_i))/k), "Total de Operações": sum(total_i), "Tempo Total": f"{sum(tempo_t):.12f}s", "Tempo/Iteração": f"{(sum(tempo_t)/k):.12f}s"}

In [451]:
bisseccao(funcao, interval, e, 1)

==========================================
            MÉTODO DA BISSECÇÃO
==========================================
╒═════════════════════╤══════════════════╕
│ Método              │ Bissecção        │
├─────────────────────┼──────────────────┤
│ Dados Iniciais      │ [1.0, 2.0]       │
├─────────────────────┼──────────────────┤
│ x̅ (raiz aproximada) │ 1.32471800       │
├─────────────────────┼──────────────────┤
│ f(x̅)                │ -0.0000018575764 │
├─────────────────────┼──────────────────┤
│ Erro x̅              │ 0.0000009536743  │
├─────────────────────┼──────────────────┤
│ Iterações           │ 20               │
├─────────────────────┼──────────────────┤
│ Operações Média     │ 10               │
├─────────────────────┼──────────────────┤
│ Operação Total      │ 209              │
├─────────────────────┼──────────────────┤
│ Tempo Total         │ 0.000068900008s  │
├─────────────────────┼──────────────────┤
│ Tempo por Iteração  │ 0.000003445000s  │
╘═════════════════════╧══════════════════╛
==========================================

{'Método': 'Bissecção',
 'Dados Iniciais': '[1.0,2.0]',
 'Raíz x̅': '1.32471752',
 'F(x̅)': '-0.0000018575764',
 'Erro em X': '0.0000009536743',
 'N° de Iterações': 20,
 'Operações/Iteração': 10,
 'Total de Operações': 209,
 'Tempo Total': '0.000068900008s',
 'Tempo/Iteração': '0.000003445000s'}

### Método 2: Método da Posição Falsa

#### Explicação do Método da Posição Falsa

Dada uma função $f(x)$ e um intervalo $[a,b]$, de forma que $f(a)\cdot f(b) < 0$.

Se pressupõe que existe apenas uma raíz no intervalo dado, então $f(x)=0$.  
O método da posição falsa não usa simplesmente uma média aritmética $\frac{a+b}{2}$, ele executa uma média aritmética ponderada entre $a$ e $b$ com os pesos $|f(a)|$ e $|f(b)|$, na seguinte forma:

$$ x = \frac{a \cdot |f(b)| + b \cdot |f(a)|}{|f(b)| + |f(a)|} = \frac {a \cdot f(b) - b \cdot f(a)}{f(b) - f(a)}$$

<div style="display: flex; justify-content: center; gap: 20px;">
  <img src="assets/atv_3/PF_a.png" width="400">
  <img src="assets/atv_3/PF_b.png" width="400">
</div>

Complexidade do Métoda da Posição Falsa:  
Diferente da Bissecção, a Posição Falsa não possuí uma fórmula para estimar seu número de iterações, visto que a redução de seu intervalo não ocorre de maneira uniforme e depende da função que está sendo usada. Além do mais, se for exigido que dois critérios de parada sejam atendidos simultaneamente, o método pode exceder um número máximo de iterações.  
Então sua complexidade pode ser medida como o número de iterações obtidas ao fim da execução do método, além do fato de que o número de iterações vai depender da função a qual está sendo usada nele.

Código para o Método da Posição Falsa:

In [452]:
# Algoritmo 2 
# Código do Método da Posição Falsa

# função para teste
def funcao(x):
    return x**3 - x - 1                                                                                 
                                                                                     # Linha 1: Os dados iniciais                                              
interval = [1.0, 2.0]                                                                # O intervalo Inicial [a,b]
e1 = 10**(-6)
e2 = e1                                                                              # precisão ε

# função propriamente

def PosicaoFalsa(func, interval, e1, e2, p):
    k = 0
    a = interval[0]
    b = interval[1]
    total_i = []
    tempo_t = []

    if abs(b-a) < e1:                                                                 # Linha 2: Condição para parada antes de iniciar a função, optei por usar o valor central entre o intervalo
        xi = (a+b)/2
        return {"Método": "Secante", "Dados Iniciais": f"[{interval[0]}, {interval[1]}]", "Raíz x̅": f"{xi:.8f}", "F(x̅)": f"{func(xi):.13f}", "Erro em X": 0, "N° de Iterações": 0, "Operações/Iteração": 0, "Total de Operações": 0, "Tempo Total": 0, "Tempo/Iteração": 0}
        # return xi

    k = 1                                                                            # Linha 3: Introdução de um iterador na função

    while abs(b-a) > e:
        time_inicial = time.perf_counter()
        i = 0

        M = func(a)                                                                  # Linha 4: variável para armazenar o valor de f(a) 
        x = (a*(func(b)) - b*(func(a))) / (func(b) - func(a))                        # Linha 5: Média ponderada da distância entre os intervalos 
        
        i += 11

        if abs(func(x)) < e2:
            i += 2
            total_i.append(i)
            media_i = round(sum(total_i)/k)
            time_final = time.perf_counter()
            tempo_t.append(time_final - time_inicial)
            error = abs(b-a)
            if p == 1:
                resultados = [ ["Método", "Posição Falsa"], ["Dados Iniciais", f"[{interval[0]}, {interval[1]}]"], ["x̅ (raiz aproximada)", f"{x:.8f}"], ["f(x̅)", f"{func(x):.13f}"], ["Erro x̅", f"{error:.7f}"], ["Iterações", k], ["Operação(M)", media_i], ["Operação Total", sum(total_i)], ["Tempo Total", f"{sum(tempo_t):.12f}s"], ["Tempo por Iteração", f"{(sum(tempo_t) / k):.12f}s"]]
                print("\n" + "="*42+"\n          MÉTODO DA POSIÇÃO FALSA\n"+"="*42)
                print(tabulate(resultados, tablefmt="fancy_grid")) 
                print("="*42 + "\n")                                                 # O retorno é o x̅, o número de iterações, o valor da função em x e o erro em x(b-a)   
                break      
            else:
                return {"Método": "Posição Falsa", "Dados Iniciais": f"[{interval[0]}, {interval[1]}]","Raíz x̅": f"{x:.8f}", "F(x̅)": f"{func(x):.13f}", "Erro em X": f"{(b-a):.13f}", "N° de Iterações": k, "Operações/Iteração": media_i, "Total de Operações": sum(total_i), "Tempo Total": f"{sum(tempo_t):.12f}s", "Tempo/Iteração": f"{(sum(tempo_t)/k):.12f}s"}
                # return x, k, func(x), (b-a)       

        if (func(x)*M) > 0:                                                          # Linha 6: Condição para que a = x
            a = x 
            i += 4
            if (b - a) < e1:                                                         # Linha 8: Condição de parada
                xi = (a+b)/2
                i += 5                                                               # Print com Tabulate
                total_i.append(i)
                media_i = round(sum(total_i)/k)
                time_final = time.perf_counter()
                tempo_t.append(time_final - time_inicial)
                error = abs(b-a)
                if p == 1:
                    resultados = [ ["Método", "Posição Falsa"], ["Dados Iniciais", f"[{interval[0]}, {interval[1]}]"], ["x̅ (raiz aproximada)", f"{x:.8f}"], ["f(x̅)", f"{func(x):.13f}"], ["Erro x̅", f"{error:.7f}"], ["Iterações", k], ["Operação(M)", media_i], ["Operação Total", sum(total_i)]]
                    print("\n" + "="*42+"\n          MÉTODO DA POSIÇÃO FALSA\n"+"="*42)
                    print(tabulate(resultados, tablefmt="fancy_grid")) 
                    print("="*42 + "\n")                                             # O retorno é o x̅, o número de iterações, o valor da função em x e o erro em x(b-a)   
                    break              
                else: 
                    return {"Método": "Secante", "Dados Iniciais": f"[{interval[0]},{interval[1]}]", "Raíz x̅": f"{x:.8f}", "F(x̅)": f"{func(x):.15f}", "Erro em X": f"{(b-a):.13f}", "N° de Iterações": k, "Operações/Iteração": media_i, "Total de Operações": sum(total_i), "Tempo Total": f"{sum(tempo_t):.12f}s", "Tempo/Iteração": f"{(sum(tempo_t)/k):.12f}s"}                      

            else:
                total_i.append(i)
                k += 1                                                               # Linha 9: Aumento da contagem do Iterador
                time_final = time.perf_counter()
                tempo_t.append(time_final - time_inicial)
        else: 
            k += 1                                                                   # Linha 9: Aumento da contagem do Iterador
            b = x 
            i += 1
            total_i.append(i)                                                                   # Linha 7: b = x
            time_final = time.perf_counter()
            tempo_t.append(time_final - time_inicial)

In [453]:
# teste 
PosicaoFalsa(funcao, interval, e1, e2, 1)

==========================================
          MÉTODO DA POSIÇÃO FALSA
==========================================
╒═════════════════════╤══════════════════╕
│ Método              │ Posição Falsa    │
├─────────────────────┼──────────────────┤
│ Dados Iniciais      │ [1.0, 2.0]       │
├─────────────────────┼──────────────────┤
│ x̅ (raiz aproximada) │ 1.32471776       │
├─────────────────────┼──────────────────┤
│ f(x̅)                │ -0.0000008290661 │
├─────────────────────┼──────────────────┤
│ Erro x̅              │ 0.6752825        │
├─────────────────────┼──────────────────┤
│ Iterações           │ 17               │
├─────────────────────┼──────────────────┤
│ Operação(M)         │ 15               │
├─────────────────────┼──────────────────┤
│ Operação Total      │ 253              │
├─────────────────────┼──────────────────┤
│ Tempo Total         │ 0.000093500006s  │
├─────────────────────┼──────────────────┤
│ Tempo por Iteração  │ 0.000005500000s  │
╘═════════════════════╧══════════════════╛
==========================================

### Método 3: Método do Ponto Fixo(MPF)

#### Explicação do Método do Ponto Fixo(MPF)

Dada uma função contínua $f(x)$ num intervalo $[a,b]$, esse intervalo detém uma raíz da equação $f(x) = 0$.  
O método baseia-se em converter essa equação numa função equivalente $x = $ φ $(x)$ e por meio de um $x_0$ inicial gerar uma sequência 
$ \{x_k \}$ para $\xi$ usando a relação $x_{k+1} = $ φ$(x_{k})$, em razão da função φ$(x)$ ser tal que $f(\xi) = 0$ para que φ $(xi) = \xi $. Dessa forma o problema torna-se encontrar um ponto fixo em φ$(x)$.

<div style="display: flex; justify-content: center; gap: 20px;">
  <img src="assets/atv_3/MPF_a.png" width="500">
</div>

Complexidade do Método do Ponto Fixo:

In [454]:
# Algoritmo 3
def funcX(x):
    return x**3 - x - 1

def funcG(x):
    return (x+1)**(1/3)
                                                            # Linha 1: Os dados iniciais                                                    
x0 = 1                                                      # (a): Valor Inicial de x0
e1 = 10 **(-6)                                              # (b): Dados de Precisão


# Função Propriamente
def MPF(x_0, e1, e2, fx, fg, p):
    total_i = []
    dado_x = x_0
    tempo_t = []

    if abs(fx(x_0)) < e1:                                   # Linha 2: Condição de parada inicial do MPF
        print(x_0)
        xi = x_0
        return {"Método": "", "Dados Iniciais": f"X₀ = {dado_x}", "Raíz x̅": f"{xi:.8f}", "F(x̅)": f"{fx(xi):.13f}", "Erro em X": 0, "N° de Iterações": 0, "Operações/Iteração": 0, "Total de Operações": 0, "Tempo Total": 0, "Tempo/Iteração": 0}
        # return xi, 0, fx(x_0), 0
    
    k = 1                                                   # Linha 3: Definição da variável de iteração 
    while abs(fx(x_0)) > e1:    
        time_inicial = time.perf_counter()
        i = 0
        x_1 = fg(x_0)                                       # Linha 4: Alteração do valor de x_1 baseado no valor de gx(x_0) 
        i += 4

        if abs(fx(x_1)) < e1 or abs(x_1 - x_0) < e2:        # Linha 5: Dada a condição x̅ = x_1
            xi = x_1
            i += 3                
            total_i.append(i)   
            time_final = time.perf_counter()
            tempo_t.append(time_final - time_inicial)
            error = abs(x_1 - x_0)

            if p == 1:                                                                                                                                    # (abs(x_1 - x_0)) / abs(x_1)
                resultados = [ ["Método", "MPF"], ["Dados Iniciais", f"X₀ = {dado_x}"], ["x̅ (raiz aproximada)", f"{xi:.8f}"], ["f(x̅)", f"{fx(xi):.13f}"], ["Erro x̅", f"{error:.13f}"], ["Iterações", k], ["Operações(M)",  round((sum(total_i)/k))], ["Operação Total", sum(total_i)], ["Tempo Total", f"{sum(tempo_t):.12f}s"], ["Tempo por Iteração", f"{(sum(tempo_t) / k):.12f}s"]]
                print("\n" + "="*42+"\n               MÉTODO DA MPF\n"+"="*42)
                print(tabulate(resultados, tablefmt="fancy_grid")) 
                print("="*42 + "\n")        
                break
            else:  
                return {"Método": "MPF", "Dados Iniciais": f"X₀ = {dado_x}", "Raíz x̅": f"{xi:.8f}", "F(x̅)": f"{fx(xi):.15f}", "Erro em X": f"{error:.13f}", "N° de Iterações": k, "Operações/Iteração": round((sum(total_i)/k)), "Total de Operações": sum(total_i), "Tempo Total": f"{sum(tempo_t):.12f}s", "Tempo/Iteração": f"{(sum(tempo_t)/k):.12f}s"} 
                # return xi, k, fx(xi), (abs(x_1 - x_0)) / abs(x_1), round((sum(total_i)/k)), sum(total_i)
        
        else:
            k += 1                                          # Linha 6: Adição no iterador
            x_0 = x_1                                       # Linha 7: Atualização do valor de x_0
            i += 1
            total_i.append(i)
            time_final = time.perf_counter()
            tempo_t.append(time_final - time_inicial)

In [455]:
# teste
MPF(x0, e1, e1, funcX, funcG, 1)

==========================================
               MÉTODO DA MPF
==========================================
╒═════════════════════╤══════════════════╕
│ Método              │ MPF              │
├─────────────────────┼──────────────────┤
│ Dados Iniciais      │ X₀ = 1           │
├─────────────────────┼──────────────────┤
│ x̅ (raiz aproximada) │ 1.32471785       │
├─────────────────────┼──────────────────┤
│ f(x̅)                │ -0.0000004737265 │
├─────────────────────┼──────────────────┤
│ Erro x̅              │ 0.0000004737265  │
├─────────────────────┼──────────────────┤
│ Iterações           │ 9                │
├─────────────────────┼──────────────────┤
│ Operações(M)        │ 5                │
├─────────────────────┼──────────────────┤
│ Operação Total      │ 47               │
├─────────────────────┼──────────────────┤
│ Tempo Total         │ 0.000025399997s  │
├─────────────────────┼──────────────────┤
│ Tempo por Iteração  │ 0.000002822222s  │
╘═════════════════════╧══════════════════╛
==========================================

### Método 4: Método de Newton-Haphson

#### Explicação do Método de Newton-Haphson

Código do Método de Newton-Haphson

<div style="display: flex; justify-content: center; gap: 20px;">
  <img src="assets/atv_3/NH_a.png" width="500">
</div>

In [472]:
# Algoritmo 4
def f(x):
    return x**3 - x - 1

def df(x):
    return 3*x**(2) - 1

                                                            # Linha 1: Dados iniciais
x0 = 0                                                      # (a): x_0 aproximação inicial
e1 = 10 ** (-6)                                             # (b): precisões e1 e e2


# Função propriamente
def NewtonHaphson(x_0, e1, e2, fx, dx, p):
    total_i = []
    tempo_t = []
    dado_x = x_0

    if abs(fx(x_0)) < e1:                                  # Linha 2: Condição inicial de parada antes do loop
        xi = x_0
        return {"Método": "", "Dados Iniciais": f"X₀ = {dado_x}", "Raíz x̅": f"{xi:.8f}", "F(x̅)": f"{fx(xi):.13f}", "Erro em X": 0, "N° de Iterações": 0, "Operações/Iteração": 0, "Total de Operações": 0, "Tempo Total": 0, "Tempo/Iteração": 0}
        # return xi, 0, f(xi)
    
    k = 1                                                   # Linha 3: Inicialização do iterador

    while abs(fx(x_0)) > e1:
        time_inicial = time.perf_counter()
        i = 0
        x_1 = x_0 - (fx(x_0) / dx(x_0))                     # Linha 4: Atualização do valor de x_1 com o novo valor de x_0
        i += 5

        if abs(fx(x_1)) < e1 or abs(x_1 - x_0) < e2:        # Linha 5: Condição de parada usando e1 e e2 
            xi = x_1
            i += 3
            total_i.append(i)
            time_final = time.perf_counter()
            tempo_t.append(time_final - time_inicial)
            error = abs(x_1 - x_0)
            if p == 1:                                                                                                                                               # (abs(x_1 - x_0)) / abs(x_1)
                resultados = [ ["Método", "Newton-Haphson"], ["Dados Iniciais", f"X₀ = {dado_x}"], ["x̅ (raiz aproximada)", f"{xi:.8f}"], ["f(x̅)", f"{fx(xi):.15f}"], ["Erro x̅", f"{error:.13f}"], ["Iterações", k], ["Operações(M)",  round((sum(total_i)/k))], ["Operação Total", sum(total_i)], ["Tempo Total", f"{sum(tempo_t):.12f}s"], ["Tempo por Iteração", f"{(sum(tempo_t) / k):.12f}s"]]
                print("\n" + "="*42+"\n            MÉTODO NEWTON-HAPHSON\n"+"="*42)
                print(tabulate(resultados, tablefmt="fancy_grid")) 
                print("="*42 + "\n")        
                break    
            else: 
                return {"Método": "Newton-Haphson", "Dados Iniciais": f"X₀={dado_x}", "Raíz x̅": f"{xi:.8f}", "F(x̅)": f"{fx(xi):.15f}", "Erro em X": f"{error:.13f}", "N° de Iterações": k, "Operações/Iteração": round((sum(total_i)/k)), "Total de Operações": sum(total_i), "Tempo Total": f"{sum(tempo_t):.12f}s", "Tempo/Iteração": f"{(sum(tempo_t)/k):.12f}s"}
                # return xi, k, fx(xi), (abs(x_1 - x_0)) / abs(x_1), round((sum(total_i)/k)), sum(total_i)
        else:
            x_0 = x_1                                        # Linha 6: Atualização do valor de x_0 com o valor obtido em x_1
            i += 1
            total_i.append(i)
            k += 1                                           # LInha 7: Atualização do iterador
            time_final = time.perf_counter()
            tempo_t.append(time_final - time_inicial)

In [457]:
# teste
NewtonHaphson(x0, e1, e1, f, df, 1)

==========================================
            MÉTODO NEWTON-HAPHSON
==========================================
╒═════════════════════╤═══════════════════╕
│ Método              │ Newton-Haphson    │
├─────────────────────┼───────────────────┤
│ Dados Iniciais      │ X₀ = 0            │
├─────────────────────┼───────────────────┤
│ x̅ (raiz aproximada) │ 1.32471796        │
├─────────────────────┼───────────────────┤
│ f(x̅)                │ 0.000000000002747 │
├─────────────────────┼───────────────────┤
│ Erro x̅              │ 0.0000008313699   │
├─────────────────────┼───────────────────┤
│ Iterações           │ 21                │
├─────────────────────┼───────────────────┤
│ Operações(M)        │ 6                 │
├─────────────────────┼───────────────────┤
│ Operação Total      │ 128               │
├─────────────────────┼───────────────────┤
│ Tempo Total         │ 0.000057200021s   │
├─────────────────────┼───────────────────┤
│ Tempo por Iteração  │ 0.000002723811s   │
╘═════════════════════╧═══════════════════╛
==========================================

### Método 5: Método da Secante

#### Explicação do método da Secante

<div style="display: flex; justify-content: center; gap: 20px;">
  <img src="assets/atv_3/SEC_a.png" width="500">
</div>

Código do Método da Secante

In [458]:
# Algoritmo 5

def f(x):
    return x**(3) - x - 1

                                                    # Linha 1: Dados iniciais

e1 = 10 ** (-6)                                     # (b): Precisões e1 e e2
e2 = e1

# Função propriamente
def Secante(x_0, x_1, e1, e2, f, p):
    total_i = []
    tempo_t = []
    dado_x0 = x_0
    dado_x1 = x_1

    if abs(f(x_0)) < e1:                            # Linha 2: Condição de parada inicial, verifica antes de entrar no loop
        xi = x_0
        return {"Método": "", "Dados Iniciais": f"X₀ = {dado_x0}, X₁ = {dado_x1}", "Raíz x̅": f"{xi:.8f}", "F(x̅)": f"{f(xi):.13f}", "Erro em X": 0, "N° de Iterações": 0, "Operações/Iteração": 0, "Total de Operações": 0, "Tempo Total": 0, "Tempo/Iteração": 0}
        # return xi
    
    if abs(f(x_1)) < e1 or abs(x_1 - x_0) < e2:     # Linha 3: Segunda condição de parada retornado x_1 dessa vez
        xi = x_1
        return {"Método": "", "Dados Iniciais": f"X₀ = {dado_x0}, X₁ = {dado_x1}", "Raíz x̅": f"{xi:.8f}", "F(x̅)": f"{f(xi):.13f}", "Erro em X": 0, "N° de Iterações": 0, "Operações/Iteração": 0, "Total de Operações": 0, "Tempo Total": 0, "Tempo/Iteração": 0}
        # return xi

    k = 1                                           # Linha 4: Inicialização do iterador
    while abs(f(x_0)) > e1:
        time_inicial = time.perf_counter()
        i = 0
        x_2 = x_1 - ( f(x_1) / (f(x_1) - f(x_0) ) ) * (x_1 - x_0) # Linha 5: x_2 recebendo seu primeiro valor baseado em x_0 e x_1
        i += 8

        if abs(f(x_2)) < e1 or abs(x_2 - x_1) < e2: # Linha 6: Condição de parada utilizando o valor de x_2
            xi = x_2
            i += 3
            total_i.append(i)
            time_final = time.perf_counter()
            tempo_t.append(time_final - time_inicial)
            error = abs(x_2 - x_1)
            if p == 1:                                                                                                                                                        #((abs(x_2 - x_1)) / abs(x_2))
                resultados = [ ["Método", "Secante"], ["Dados Iniciais", f"X₀ = {dado_x0}, X₁ = {dado_x1}"], ["x̅ (raiz aproximada)", f"{xi:.8f}"], ["f(x̅)", f"{f(xi):.15f}"], ["Erro x̅", f"{error:.13f}"], ["Iterações", k], ["Operações(M)",  round((sum(total_i)/k))], ["Operação Total", sum(total_i)], ["Tempo Total", f"{sum(tempo_t):.12f}s"], ["Tempo por Iteração", f"{(sum(tempo_t) / k):.12f}s"]]
                print("\n" + "="*42+"\n           MÉTODO DA SECANTE\n"+"="*42)
                print(tabulate(resultados, tablefmt="fancy_grid")) 
                print("="*42 + "\n")        
                break 
            else:
                return {"Método": "Secante", "Dados Iniciais": f"X₀={dado_x0}, X₁={dado_x1}", "Raíz x̅": f"{xi:.8f}", "F(x̅)": format(f(xi), ".12f"), "Erro em X": f"{error:.13f}", "N° de Iterações": k, "Operações/Iteração": round((sum(total_i)/k)), "Total de Operações": sum(total_i), "Tempo Total": f"{sum(tempo_t):.12f}s", "Tempo/Iteração": f"{(sum(tempo_t)/k):.12f}s"}
                # return xi, f(x_2), k
        else:
            x_0 = x_1                               # Linha 7: Atualização de x_0 e x_1
            x_1 = x_2   
            k += 1                                  # Linha 8: Atualização do iterador
            i += 2                            
            total_i.append(i)
            time_final = time.perf_counter()
            tempo_t.append(time_final - time_inicial)

In [459]:
# teste
Secante(0,0.5, e1, e2, f, 0)

{'Método': 'Secante',
 'Dados Iniciais': 'X₀=0, X₁=0.5',
 'Raíz x̅': '1.32471795',
 'F(x̅)': '-0.000000043406',
 'Erro em X': '0.0000119166137',
 'N° de Iterações': 26,
 'Operações/Iteração': 10,
 'Total de Operações': 261,
 'Tempo Total': '0.000155899994s',
 'Tempo/Iteração': '0.000005996154s'}

### Tabelas Comparativas:

#### TABELA $1^{(18)}$:
Dados iniciais:  
$f(x) = e^{-x^2} - \cos(x)$  
O intervalo: $\bar{x} \in (1,2)$  
A precisão: $\epsilon_{1} = \epsilon_{2} = 10^{-4}$

In [460]:
# Função f(x) que será usada
def f18(x):
    return (math.exp(-x**(2)) - math.cos(x))
# Função g(x) que será usada no MPF
def g18(x):
    return math.cos(x) - math.exp(-x**(2)) + x
# Função derivada de f(x)
def d18(x):
    return (-2)*x*(math.exp(-x**(2))) + math.sin(x)
# Dados usados
intervalo = [1, 2]          # Intervalo
e18 = 10 ** (-4)            # Precisão
x0 = 1.5                    # x0 usado no MPF e no método Newton
x_s0 = 1                    # x0 usado na Secante
x_s1 = 2                    # x1 usado na Secante
p = 0                       # p é a variável que define se é impresso ou não a tabela

In [461]:
tabela_18 = []
tabela_18.append(bisseccao(f18, intervalo, e18, 0))
tabela_18.append(PosicaoFalsa(f18, intervalo, e18, e18, 0))
tabela_18.append(MPF(x0, e18, e18, f18, g18, 0))
tabela_18.append(NewtonHaphson(x0, e18, e18, f18, d18, 0))
tabela_18.append(Secante(x_s0, x_s1, e18, e18, f18, 0))
df = pd.DataFrame(tabela_18).set_index("Método").T # O nome dos métodos não são originalmente colunas, então eu faço a transposta df

##### Resultado da Tabela 18 para os métodos, no seguinte formato:

In [462]:
df

Método,Bissecção,Posição Falsa,MPF,Newton-Haphson,Secante
Dados Iniciais,"[1,2]","[1, 2]",X₀ = 1.5,X₀=1.5,"X₀=1, X₁=2"
Raíz x̅,1.44744873,1.44735707,1.44752471,1.44741635,1.44741345
F(x̅),0.0000219211804,-0.0000363875857,0.000070257776854,0.000001320435745,-0.000000524225
Erro em X,0.0000610351562,0.5528852215528,0.0001931866074,0.0017071527611,0.0001855289483
N° de Iterações,15,6,6,2,5
Operações/Iteração,10,15,5,7,10
Total de Operações,144,88,32,14,51
Tempo Total,0.000050899987s,0.000029899995s,0.000019100000s,0.000013999997s,0.000015400001s
Tempo/Iteração,0.000003393332s,0.000004983332s,0.000003183333s,0.000006999999s,0.000003080000s

#### TABELA $2^{(19)}$:
Dados iniciais:  
$f(x) = x^{3} - x - 1$  
O intervalo: $\bar{x} \in (1,2)$  
A precisão: $\epsilon_{1} = \epsilon_{2} = 10^{-6}$

In [477]:
def f19(x):
    return x**3 - x - 1 
# Função g(x) que será usada no MPF
def g19(x):
    return (x+1)**(1/3)
# Função derivada de f(x)
def d19(x):
    return 3*x**(2) - 1
# Dados usados
intervalo = [1, 2]      # Intervalo
e19 = 10 ** (-6)        # Precisão
x0 = 1                  # x0 usado no MPF 
x0_n = 0                # x0 no método Newton
x_s0 = 0                # x0 usado na Secante
x_s1 = 0.5              # x1 usado na Secante
p = 0                   # p é a variável que define se é impresso ou não a tabela

In [479]:
tabela_19 = []
tabela_19.append(bisseccao(f19, intervalo, e19, 0))
tabela_19.append(PosicaoFalsa(f19, intervalo, e19, e19, 0))
tabela_19.append(MPF(x0, e19, e19, f19, g19, 0))
tabela_19.append(NewtonHaphson(x0_n, e19, e19, f19, d19, 0))
tabela_19.append(Secante(x_s0, x_s1, e19, e19, f19, 0))
df = pd.DataFrame(tabela_19).set_index("Método").T # O nome dos métodos não são originalmente colunas, então eu faço a transposta df

In [480]:
df

Método,Bissecção,Posição Falsa,MPF,Newton-Haphson,Secante
Dados Iniciais,"[1,2]","[1, 2]",X₀ = 1,X₀=0,"X₀=0, X₁=0.5"
Raíz x̅,1.32471752,1.32471776,1.32471785,1.32471796,1.32471795
F(x̅),-0.0000018575764,-0.0000008290661,-0.000000473726474,0.000000000002747,-0.000000043406
Erro em X,0.0000009536743,0.6752825012209,0.0000004737265,0.0000008313699,0.0000119166137
N° de Iterações,20,17,9,21,26
Operações/Iteração,10,15,5,6,10
Total de Operações,209,253,47,128,261
Tempo Total,0.000045500004s,0.000087100001s,0.000019399988s,0.000056200006s,0.000081300008s
Tempo/Iteração,0.000002275000s,0.000005123529s,0.000002155554s,0.000002676191s,0.000003126923s

#### TABELA $3^{(20)}$:
Dados iniciais:  
$f(x) = 4\cdot \sin(x) - e^{x}$  
O intervalo: $\bar{x} \in (0,1)$  
A precisão: $\epsilon_{1} = \epsilon_{2} = 10^{-5}$

In [466]:
def f20(x):
    return 4 * math.sin(x) - math.e**x
# Função g(x) que será usada no MPF
def g20(x):
    return x - 2 * math.sin(x) + .5 * math.e**x
# Função derivada de f(x)
def d20(x):
    return 4*(math.cos(x)) - (math.exp(x))
# Dados usados
intervalo = [0, 1]      # Intervalo
e20 = 10 ** (-5)        # Precisão
x0 = 0.5                # x0 usado no MPF 
x0_n = 0.5              # x0 no método Newton
x_s0 = 0                # x0 usado na Secante
x_s1 = 1                # x1 usado na Secante
p = 0                   # p é a variável que define se é impresso ou não a tabela

In [467]:
tabela_20 = []
tabela_20.append(bisseccao(f20, intervalo, e20, 0))
tabela_20.append(PosicaoFalsa(f20, intervalo, e20, e20, 0))
tabela_20.append(MPF(x0, e20, e20, f20, g20, 0))
tabela_20.append(NewtonHaphson(x0_n, e20, e20, f20, d20, 0))
tabela_20.append(Secante(x_s0, x_s1, e20, e20, f20, 0))
df = pd.DataFrame(tabela_20).set_index("Método").T # O nome dos métodos não são originalmente colunas, então eu faço a transposta df

In [468]:
df

Método,Bissecção,Posição Falsa,MPF,Newton-Haphson,Secante
Dados Iniciais,"[0,1]","[0, 1]",X₀ = 0.5,X₀=0.5,"X₀=0, X₁=1"
Raíz x̅,0.37055206,0.37055883,0.37055611,0.37055808,0.37055810
F(x̅),-0.0000137550016,0.0000016698063,-0.000004519360954,-0.000000027834957,0.000000005260
Erro em X,0.0000076293945,0.3705628166565,0.0000161439720,0.0001386326362,0.0000057406394
N° de Iterações,17,8,5,3,7
Operações/Iteração,11,12,5,7,10
Total de Operações,191,97,27,20,71
Tempo Total,0.001637800007s,0.000049800008s,0.000014899997s,0.000026399997s,0.000027199989s
Tempo/Iteração,0.000096341177s,0.000006225001s,0.000002979999s,0.000008799999s,0.000003885713s

#### TABELA $4^{(21)}$:
Dados iniciais:  
$f(x) = x\cdot \log(x) - 1$  
O intervalo: $\bar{x} \in (2,3)$  
A precisão: $\epsilon_{1} = \epsilon_{2} = 10^{-7}$

In [481]:
def f21(x):
    return x * math.log10(x) - 1 
# Função g(x) que será usada no MPF
def g21(x):
    return x - (1.3) * ((x * math.log10(x)) - 1)
# Função derivada de f(x)
def d21(x):
    return math.log10(x) + 1 / math.log(10)
# Dados usados
intervalo = [2, 3]      # Intervalo
e21 = 10 ** (-7)        # Precisão
x0 = 2.5                # x0 usado no MPF 
x0_n = 2.5              # x0 no método Newton
x_s0 = 2.3              # x0 usado na Secante
x_s1 = 2.7              # x1 usado na Secante
p = 0                   # p é a variável que define se é impresso ou não a tabela

In [482]:
tabela_21 = []
tabela_21.append(bisseccao(f21, intervalo, e21, 0))
tabela_21.append(PosicaoFalsa(f21, intervalo, e21, e21, 0))
tabela_21.append(MPF(x0, e21, e21, f21, g21, 0))
tabela_21.append(NewtonHaphson(x0_n, e21, e21, f21, d21, 0))
tabela_21.append(Secante(x_s0, x_s1, e21, e21, f21, 0))
df = pd.DataFrame(tabela_21).set_index("Método").T # O nome dos métodos não são originalmente colunas, então eu faço a transposta df

In [483]:
df #Newton está dando valores estranhos

Método,Bissecção,Posição Falsa,MPF,Newton-Haphson,Secante
Dados Iniciais,"[2,3]","[2, 3]",X₀ = 2.5,X₀=2.5,"X₀=2.3, X₁=2.7"
Raíz x̅,2.50618416,2.50618403,2.50618417,2.50618415,2.50618418
F(x̅),0.0000000126001,-0.0000000992799,0.000000020508266,0.000000000001378,0.000000029153
Erro em X,0.0000000596046,0.4938184417156,0.0000003200582,0.0000039881366,0.0000805609321
N° de Iterações,25,5,5,2,3
Operações/Iteração,10,15,5,7,10
Total de Operações,240,73,27,14,31
Tempo Total,0.000055099968s,0.000029999988s,0.000013400000s,0.000087799999s,0.000010500000s
Tempo/Iteração,0.000002203999s,0.000005999998s,0.000002680000s,0.000043900000s,0.000003500000s

In [485]:
Estimativa_Bisseccao([2,3], 10**(-7))

O número provável de iterações é: (23)

#### TABELA $5^{(22)}$:
Dados iniciais:  
$f(x) = x^{3} - 3.5\cdot x^{2} + 4\cdot x -1.5 = (x-1)^{2} \cdot (x-1.5)$  
O intervalo: $\bar{x} \in (2,3)$  
A precisão: $\epsilon_{1} = \epsilon_{2} = 10^{-7}$  
Teste usando apenas o método de Newton-Haphson

In [503]:
def f22(x):
    return ((x-1)**2)*(x-1.5)

def d22(x):
    return 3*x**(2) - 7*x + 4

# Dados usados
e22 = 10 ** (-7)        # Precisão dada no livro
x0_n1 = .5              # x0 no método Newton1
x0_n2 = 1.33333
x0_n3 = 1.33334
p = 0                   # p é a variável que define se é impresso ou não a tabela

In [504]:
tabela_22 = []
tabela_22.append(NewtonHaphson(x0_n1, e22, e22, f22, d22, 0))
tabela_22.append(NewtonHaphson(x0_n2, e22, e22, f22, d22, 0))
tabela_22.append(NewtonHaphson(x0_n3, e22, e22, f22, d22, 0))
df = pd.DataFrame(tabela_22).set_index("Método").T # O nome dos métodos não são originalmente colunas, então eu faço a transposta df

In [505]:
df

Método                  Newton-Haphson      Newton-Haphson     Newton-Haphson
Dados Iniciais                  X₀=0.5          X₀=1.33333         X₀=1.33334
Raíz x̅                     0.99955313          0.99970901         1.50000000
F(x̅)               -0.000000099935163  -0.000000042363633  0.000000001224128
Erro em X              0.0004460737276     0.0002906570882    0.0000349863126
N° de Iterações                     11                  35                 27
Operações/Iteração                   6                   6                  6
Total de Operações                  68                 212                164
Tempo Total            0.000036300022s     0.000096399985s    0.000227299992s
Tempo/Iteração         0.000003300002s     0.000002754285s    0.000008418518s

## B $)$

<div style="display: flex; justify-content: center; gap: 20px;">
  <img src="assets/atv_3/adaptar.png" width="400">
</div>

### Adaptação do pseudo código acima para o método da Secante e do MPF:

#### Método para o valor de Polinômios:

In [11]:
def polinomio(a, x):
    return sum([a[i] * (x ** i) for i in range(len(a))])
# É uma compressão de lista que por fim soma tudo internamente
# O 'i' vai de 0 até o tamanho da lista 'a' e a cada indíce é pego um valor da lista 'a' e
# o multiplica por (x ** i), após o laço a lista inteira é somada e retorna um valor

#### Método da Secante adaptado para o pseudo-código

In [ ]:
# Secante Atualizada

def Secante_Adaptada(a, x0, x1, e1, e2, itmax, fx):
    tempo_i = []

    # Avaliação inicial
    p0 = polinomio(a, x0)

    for k in range(1, itmax + 1):
        t_inicial = time.perf_counter()
        # b = p(x1)
        b = polinomio(a, x1)

        # Critério de parada 1
        if abs(b) <= e1:
            t_final = time.perf_counter()
            tempo_i.append(t_final - t_inicial)
            return {"Método": "Secante", "Raíz X": f"{x1:.12f}", "F(X)": f"{fx(x1):.12f}", "N° de Iterações": k, "Tempo/Iteração": f"{(sum(tempo_i)/k):.12f}", "Tempo Total": f"{sum(tempo_i):.12f}"}

        # c = derivada aproximada (secante)
        c = (b - p0) / (x1 - x0)

        # Correção (passo da secante)
        deltax = b / c
        x2 = x1 - deltax

        # Critério de parada 2
        if abs(deltax) <= e2:
            return {"Método": "Secante", "Raíz X": f"{x2:.12f}", "F(X)": f"{fx(x2):.12f}", "N° de Iterações": k, "Tempo/Iteração": f"{(sum(tempo_i)/k):.12f}", "Tempo Total": f"{sum(tempo_i):.12f}"}

        #
        x0 = x1
        p0 = b
        x1 = x2
        t_final = time.perf_counter()
        tempo_i.append(t_final - t_inicial)
    print(f"O método da Secante não convergiu com {itmax} iterações")

#### Método do Ponto Fixo adaptado para o pseudo-código

In [8]:
def phi(a, x):
    return (x + 1) ** (1/3)

In [9]:
def mpf_polinomio(a, x0, e1, e2, itmax, g):
    tempo_i = []
    x = x0

    for k in range(1, itmax + 1):
        t_inicial = time.perf_counter()
        # b = P(x)
        b = polinomio(a, x)

        # Critério 1: valor da função
        if abs(b) <= e1:
            t_final = time.perf_counter()
            tempo_i.append(t_final - t_inicial)
            
            return {"Raíz X": f"{x:.12f}", "F(X)": f"{b:.12f}", "N° de Iterações": k, "Tempo/Iteração": f"{(sum(tempo_i)/k):.12f}", "Tempo Total": f"{sum(tempo_i):.12f}"}

        # Iteração do ponto fixo
        x_new = g(a, x)

        # deltax = x_{k+1} - x_k
        deltax = x_new - x

        # Atualização
        x = x_new

        # Critério 2: estabilidade
        if abs(deltax) <= e2:
            t_final = time.perf_counter()
            tempo_i.append(t_final - t_inicial)
            return {"Método": "Ponto Fixo", "Raíz X": f"{x:.12f}", "F(X)": f"{polinomio(a, x):.12f}", "N° de Iterações": k, "Tempo/Iteração": f"{(sum(tempo_i)/k):.12f}", "Tempo Total": f"{sum(tempo_i):.12f}"}

    print(f"O método da Secante não convergiu com {itmax} iterações")

In [5]:
e1 = 10 ** (-6)

def fx(x):
    return x**3 - 3*x + 3 

def gx(a, x):
    return (3*x - 3) ** (1/3)


a = [3, -3, 0, 1]

x0 = - 0.8
x1 = 1.5

In [16]:
tabela_adaptar = []
tabela_adaptar.append(Secante_Adaptada(a, x0, x1, e1, e1, 30, fx))
tabela_adaptar.append(mpf_polinomio(a, x0, e1, e1, 50, gx))

df = pd.DataFrame(tabela_adaptar).set_index("Método").T # O nome dos métodos não são originalmente colunas, então eu faço a transposta df

O método da Secante não convergiu com 30 iterações

KeyError: "None of ['Método'] are in the columns"

In [55]:
df

Método                   Secante                       Ponto Fixo
Raíz X           -2.103803402754   1.051901923856+0.565236432752j
F(X)             -0.000000000194  -0.000002215114+0.000000422416j
N° de Iterações               41                               40
Tempo/Iteração    0.000000797561                   0.000000030000
Tempo Total       0.000032699987                   0.000001199995